### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by eng-eng11**

### CODE REVIEW

**Comment by Oghenebrume50** [comment]
Hi team,  you guys did a very good job, everything is okay, please merge to master and submit the project completion form, check out [Github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) and use it for your next project. Good luck.

**Comment by jelduran** [comment]
Thank you @Oghenebrume50, I thought we were using Github workflow, can you explain us why we were not?

**Comment by Oghenebrume50** [comment]
Hi, did you check out the link? Anyways basically what you should be doing is creating feature branches with descriptive names of the problem you are solving. Your branch should not be titled development. But check out that link for more clarification

**Comment by jelduran** [comment]
Ok, thank you so much! We are going to merge to master branch now!

**Pull request merged**
